In [1]:
import torch
from torch import nn
from custombatchnorm import customBatchNorm
from customlinear import customLinear
from customdropout import customDropout
from customrelu import customRelu
from customsigmoid import customSigmoid
from customsoftmax import customSoftmax
from custommedianfilter import custom_median_filter

In [2]:
input_size = 10
output_size = 2

# EX 1.1 Реализуйте слой BatchNorm (nn.BatchNorm).

In [5]:
X = torch.rand(input_size, output_size) + 100
custombatchnormlayer = customBatchNorm(2)
print(custombatchnormlayer(X, training=True))

tensor([[ 0.1511,  0.5954],
        [-0.8417, -0.9203],
        [-0.0230, -0.5061],
        [-0.7668,  0.4772],
        [-0.5356,  0.4615],
        [ 1.6440, -0.4921],
        [ 1.1571,  0.3590],
        [ 1.3443,  1.7473],
        [-1.4353, -2.1245],
        [-0.6942,  0.4028]])


ref:
1. https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm2d.html

# EX 1.2 Реализуйте слой Linear (nn.Linear).

In [3]:
customlinearlayer = customLinear(input_size, output_size)
torchlinearlayer = nn.Linear(input_size, output_size)

customlinearlayer.w.data.copy_(torchlinearlayer.weight.T)
customlinearlayer.b.data.copy_(torchlinearlayer.bias)

tensor([-0.2773, -0.1272], grad_fn=<CopyBackwards>)

In [4]:
X = torch.rand(input_size)
print(f'customs output = {customlinearlayer(X)} torchs output = {torchlinearlayer(X)}')

customs output = tensor([ 0.1352, -0.1092]) torchs output = tensor([ 0.1352, -0.1092], grad_fn=<ViewBackward0>)


ref:
1) https://pytorch.org/docs/stable/generated/torch.nn.Linear.html
2) https://www.toppr.com/guides/python-guide/references/methods-and-functions/methods/built-in/python-callable/

# EX 1.3 Реализуйте слой Dropout(nn.Dropout).

In [5]:
X = torch.rand(input_size)

In [9]:
customdropoutlayer = customDropout(p = 0.8)
print(f'X = {X}, \n customdropoutlayer result = {customdropoutlayer(X)}')

X = tensor([0.1833, 0.6547, 0.3483, 0.3201, 0.5643, 0.8514, 0.0011, 0.8552, 0.3144,
        0.1215]), 
 customdropoutlayer result = tensor([0.1833, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000])


ref: 
1) https://pytorch.org/docs/stable/generated/torch.nn.Dropout.html

# EX 1.4 Реализуйте одно или более из:

    слой ReLU(nn.ReLU)
    слой Sigmoid(nn.Sigmoid)
    слой Softmax(nn.Softmax)


In [8]:
X = torch.randn(input_size, output_size)

customrelu = customRelu()
customsigmoid = customSigmoid()
customsoftmax = customSoftmax()

print(f'custom: relu result = {customrelu(X)} \n sigmoid result = {customsigmoid(X)} \n softmax result =  {customsoftmax(X)}')

relu result = tensor([[1.3558, 0.7316],
        [0.0000, 0.5896],
        [0.7719, 0.0000],
        [0.0000, 0.5984],
        [0.0000, 0.9217],
        [0.0000, 0.0000],
        [0.0000, 0.7951],
        [0.5306, 1.4592],
        [0.9442, 0.0000],
        [0.0000, 0.0000]]) 
 sigmoid result = tensor([[0.7951, 0.6752],
        [0.4976, 0.6433],
        [0.6839, 0.3520],
        [0.2076, 0.6453],
        [0.3333, 0.7154],
        [0.0873, 0.4857],
        [0.4371, 0.6889],
        [0.6296, 0.8114],
        [0.7199, 0.3010],
        [0.1669, 0.4912]]) 
 softmax result =  tensor([[0.6512, 0.3488],
        [0.3545, 0.6455],
        [0.7994, 0.2006],
        [0.1259, 0.8741],
        [0.1659, 0.8341],
        [0.0920, 0.9080],
        [0.2596, 0.7404],
        [0.2832, 0.7168],
        [0.8566, 0.1434],
        [0.1719, 0.8281]])


In [9]:
torchrelu = torch.nn.ReLU()
torchsigmoid = torch.nn.Sigmoid()
torchsoftmax = torch.nn.Softmax()

print(f'torch: relu result = {torchrelu(X)} \n sigmoid result = {torchsigmoid(X)} \n softmax result =  {torchsoftmax(X)}')

torch: relu result = tensor([[1.3558, 0.7316],
        [0.0000, 0.5896],
        [0.7719, 0.0000],
        [0.0000, 0.5984],
        [0.0000, 0.9217],
        [0.0000, 0.0000],
        [0.0000, 0.7951],
        [0.5306, 1.4592],
        [0.9442, 0.0000],
        [0.0000, 0.0000]]) 
 sigmoid result = tensor([[0.7951, 0.6752],
        [0.4976, 0.6433],
        [0.6839, 0.3520],
        [0.2076, 0.6453],
        [0.3333, 0.7154],
        [0.0873, 0.4857],
        [0.4371, 0.6889],
        [0.6296, 0.8114],
        [0.7199, 0.3010],
        [0.1669, 0.4912]]) 
 softmax result =  tensor([[0.6512, 0.3488],
        [0.3545, 0.6455],
        [0.7994, 0.2006],
        [0.1259, 0.8741],
        [0.1659, 0.8341],
        [0.0920, 0.9080],
        [0.2596, 0.7404],
        [0.2832, 0.7168],
        [0.8566, 0.1434],
        [0.1719, 0.8281]])


/home/uncookie/anaconda3/envs/ersote/lib/python3.11/site-packages/torch/nn/modules/module.py:1532: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


ref:

1. https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html
2. https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html
3. https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html

# EX 2 Реализуйте медианный фильтр. Для текущего пикселя, пиксели, которые «попадают» в матрицу, сортируются, и выбирается медианное значение из отсортированного массива. Это значение и является выходным для текущего пикселя. Используйте только чистый torch. Покажите результат на примере для размера ядра 3, 5, 10

In [2]:
image = torch.randint(0, 256, (1, 10, 10), dtype=torch.float32)

output_3 = custom_median_filter(image, 3)
output_5 = custom_median_filter(image, 5)
output_10 = custom_median_filter(image, 10)

print("Исходное изображение:\n", image)
print("\n Отфильтрованное изображение (ядро 3):\n", output_3)
print("\n Отфильтрованное изображение (ядро 5):\n", output_5)
print("\n Отфильтрованное изображение (ядро 10):\n", output_10)

Исходное изображение:
 tensor([[[135.,  69., 186.,  57., 143., 128.,  82., 236., 107.,  37.],
         [146., 252., 176., 201.,  26., 137., 252.,  17., 143.,   1.],
         [228., 209.,   8., 131., 252., 224., 170.,  92., 101.,  39.],
         [129.,  82., 178., 143., 123.,  48.,   0.,  31., 153., 155.],
         [  7.,  23.,  81.,  98., 226.,  81., 169.,  86.,  12., 229.],
         [227.,  12., 121., 135., 217., 205., 163., 156.,  33., 183.],
         [212.,  76.,  40., 159.,  77., 205., 193., 202., 205., 209.],
         [ 53., 195., 109., 169., 113.,  63., 229., 188.,  79., 177.],
         [ 92., 113., 239., 161., 226., 106., 119., 157., 149.,  88.],
         [252.,  80.,  22.,   2.,  90.,  98., 120.,  77.,  82., 228.]]])

 Отфильтрованное изображение (ядро 3):
 tensor([[[135., 146., 176., 143., 128., 128., 128., 107., 107.,  37.],
         [146., 176., 176., 143., 137., 143., 137., 107.,  92.,  39.],
         [146., 176., 176., 143., 137., 137.,  92., 101.,  92., 101.],
         [1